version: "1.0.0"
web2api:
  min: "0.1.0"
requires_env:
  - BIRD_AUTH_TOKEN
  - BIRD_CT0
dependencies:
  commands:
    - bird
  apt:
    - nodejs
  npm:
    - "@steipete/bird"
healthcheck:
  command:
    - bird
    - --version
