name: "X (Twitter)"
slug: "x"
base_url: "https://x.com"
description: "Retrieve recent posts from an X/Twitter user profile"
endpoints:
  posts:
    description: "Get recent posts by username (q=username, count=N)"
    requires_query: true
    url: "https://x.com/{query}"
    items:
      container: "[data-testid='tweet']"
      fields:
        text:
          selector: "[data-testid='tweetText']"
          attribute: "text"
    pagination:
      type: "page_param"
      param: "p"
      start: 1
